--select * (columns), function as (name of the new column) 
--from table
--where (condition)
--group by column1, column2
--having (condition o aggregate)
--order by (column to work on) ASC/DEC

select * from customer_shopping

--Questions to Answer
--Q1: What is the total revenue generated by male vs women?

select gender, sum(purchase_amount) as revenue
from customer_shopping
group by gender

--Q2: Which customer used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer_shopping
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_shopping)
order by purchase_amount desc

--Q3: What are the top 5 products with the highest average review rating?

select top 5 item_purchased, round(avg(review_rating),2) as "Review Rating"
from customer_shopping
group by item_purchased
order by avg(review_rating) desc

--Q4: Compare the average purchase amount between Standard and Express shipping.

select shipping_type, round(avg(purchase_amount),2) as Revenue
from customer_shopping
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Q5: Do subscribed customrs spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, count(customer_id), sum(purchase_amount) as Total_Revenue, 
avg(purchase_amount) as Average_spend
from customer_shopping
where subscription_status in ('yes', 'no')
group by subscription_status 

--Q6: Which 5 products have the highest percentage of purchase with discount appiled.

select top 5 item_purchased, 
100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*) as discount_rate
from customer_shopping
group by item_purchased
order by discount_rate


--Q7: Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
-- to query, create a table called customer_type. Then a column 
--called Customer_segment where the labels are inputted

with customer_type as (
select customer_id, previous_purchases, 
case 
	when previous_purchases = 1 then 'New_Customer' 
	when previous_purchases between 2 and 5 then 'Returning_Customer' 
	else 'Loyal_customer'
	end as Customer_segment
from customer_shopping)

select customer_segment, count(*) as 'Number of customers'
from customer_type
group by Customer_segment 

--Q8: What are the top 3 most purchased products in each category?
--first, rank products by category. then pick from there

with item_counts as (
select item_purchased, category,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping
group by item_purchased, category
)

select item_rank,item_purchased, category, total_orders
from item_counts
WHERE item_rank <= 3

--Q9: Are customers who are repeat buyers (more han 5 times) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping 
where previous_purchases >5
group by subscription_status

--Q10: What is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as total_revenue
from customer_shopping
group by age_group